services:
  crawler:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=${PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD:-0}
      - DB_USERNAME=${DB_USERNAME:-lazuli}
      - DB_PASSWORD=${DB_PASSWORD:-x1RWo6cqFtHiaAHce5HB}
      - DB_HOST=${DB_HOST:-mongo}
      - DB_PORT=${DB_PORT:-27017}
      - USER_AGENT=${USER_AGENT:-PostmanRuntime/7.37.3}
      - APP_ENV=${APP_ENV:-production}
      - API_USERNAME=${API_USERNAME:-lazuli}
      - API_PASSWORD=${API_PASSWORD:-ninja}
      - GCP_CREDENTIALS_PATH=${GCP_CREDENTIALS_PATH:-/app/gcp-file-upload-key.json}
    depends_on:
      - mongo
    volumes:
      - .:/app  # Sync current directory with /app in the container
      - /app/go/pkg/mod  # Cache Go modules for faster builds
      - /app/node_modules  # Cache Node.js modules for faster builds

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME:-lazuli}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD:-x1RWo6cqFtHiaAHce5HB}
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
